name: Deploy to AWS ECS
on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest
  ECS_CLUSTER: RkDevCluster
  ECS_SERVICE: mynodeappservice
  ECS_TASK_DEFINITION: .aws/mynodejsapptaskdef.json
  CONTAINER_NAME: nodejsappcont
  REGION: us-east-1
  TASK_FAMILY: mynodejsapptaskdef


jobs:
  buildAnddeploy:
    name: Build & Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Running Lint
        run: echo "Lint...."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          
      - name: container image name
        run: echo ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG 

      - name: Deploy to ECS
        run: |
            aws configure set region $REGION
            echo ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
            TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY" --region "us-east-1")
            NEW_CONTAINER_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
            echo "Registering new container definition..."
            aws ecs register-task-definition --region "us-east-1" --family "${TASK_FAMILY}" --container-definitions "${NEW_CONTAINER_DEFINTIION}"
            echo "Updating the Node 2025 TryApp service..."
            aws ecs update-service --region "us-east-1" --cluster RkDevCluster --service mynodeappservice --task-definition "${TASK_FAMILY}"